Add Equals() bloq
quantumlib/Qualtran pull request #1411
Opened 2024-09-19 16:48 UTC by fpapa250

Adds bloq to check if two quantum registers are equal.

2024-09-19 17:04 UTC, NoureldinYosri requested changes
please don't use QAny instead take a dtype as input

2024-09-19 22:17 UTC, anurudhp commented on qualtran/bloqs/arithmetic/comparison.py
> +            y = bb.join(y_split, self.dtype)
You can use the `MultiControlX` bloq to simplify the decomposition: https://github.com/quantumlib/Qualtran/blob/db8b9938d8210024bb6b92942376363586165efc/qualtran/bloqs/mcmt/multi_control_pauli.py#L183

2024-09-19 22:18 UTC, anurudhp commented on qualtran/bloqs/arithmetic/comparison.py
> +            }
Return a `dict` instead of a set: e.g. `{Xor(...): 2, ...}`

2024-09-23 13:32 UTC, NoureldinYosri requested changes
almost there

2024-09-23 13:32 UTC, NoureldinYosri commented on qualtran/bloqs/arithmetic/comparison.py
> +        x: Bitsize-sized input register.
thre is no bitsize. you can just say
```
x: first input register.
y: second input register.
```

2024-09-23 13:32 UTC, NoureldinYosri commented on qualtran/bloqs/arithmetic/comparison.py
> +    Args:
add empty lines between the different sections here and below
```suggestion

    Args:
```

2024-09-23 13:32 UTC, NoureldinYosri commented on qualtran/bloqs/arithmetic/comparison.py
> +        return {
`.bloq_counts` will fail for symbolic inputs.

you can support symbolic bloq_counts like this https://github.com/quantumlib/Qualtran/blob/db8b9938d8210024bb6b92942376363586165efc/qualtran/bloqs/arithmetic/multiplication.py#L593

2024-09-23 17:36 UTC, NoureldinYosri approved these changes

2024-09-23 18:23 UTC, NoureldinYosri commented on qualtran/bloqs/arithmetic/comparison.py
> +            cvs = [0] * self.bitsize
```suggestion
            cvs: Union[HasLength, Sequence[int]] = [0] * self.bitsize
```

2024-09-23 18:23 UTC, NoureldinYosri commented on qualtran/bloqs/arithmetic/comparison_test.py
> +        target=QBit().get_classical_domain(),
```suggestion
        target=range(2),
```

2024-09-23 18:26 UTC, NoureldinYosri commented on qualtran/bloqs/arithmetic/comparison.py
> +        if self.is_symbolic():
either explicitly test that self.bitsize is symblic here or add the type guard https://github.com/quantumlib/Qualtran/blob/db8b9938d8210024bb6b92942376363586165efc/qualtran/symbolics/types.py#L73

2024-09-24 06:44 UTC, merged