Bloq Quickstarter
quantumlib/Qualtran pull request #456
Opened 2023-10-26 17:47 UTC by mpharrigan

A single-page vanilla-javascript little app that will produce some of the boilerplate for bootstrapping a new bloq.

<img width="1025" alt="image" src="https://github.com/quantumlib/Qualtran/assets/4967059/6c5d5405-9660-45a6-a0cd-cc9aa72ed689">

2023-10-26 17:54 UTC, fdmalone requested changes
very cool

2023-10-26 23:00 UTC, mpharrigan commented on dev_tools/bloq-quickstarter.html
> +        return f'${className}'
is that a thing that happens?

2023-10-27 05:10 UTC, fdmalone commented on dev_tools/bloq-quickstarter.html
> +        return f'${className}'
(copied code to gen_bloq.py and ran format_incremental)
gen_bloq.py:34:15: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
gen_bloq.py:2:0: W0611: Unused Union imported from typing (unused-import)
gen_bloq.py:6:0: W0611: Unused Side imported from qualtran (unused-import)

Anyway, this is not really important, it's mean to be a quickstart, not a complete bloq.

2023-10-27 17:03 UTC, mpharrigan commented on dev_tools/bloq-quickstarter.html
> +        return f'${className}'
I'll remove the fstring part. The unused imports are sortof part of it as it's easier to prune unused imports than add ones that are missing -- at least in the context of a quickstarter

2023-10-27 17:23 UTC, fdmalone approved these changes
LGTM

2023-10-27 17:24 UTC, fdmalone commented
Are these bot warnings something to worry about?

2023-10-27 17:31 UTC, mpharrigan commented on dev_tools/bloq-quickstarter.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
fixed

2023-10-27 17:34 UTC, mpharrigan commented
I'm pretty sure the fact that I'm putting all the user input through `hljs.highlight` and its wrapped in `<pre><code>` means you can't inject anything nefarious. In fact-- I put in a sanitizer but then whenever you would type a "<" in the input field it would literally turn up as `&lt;` in the code block.

I changed the way the code is organized so maybe the analyzer can see that all user input is being funneled through `hljs.highlight` which hopefully it knows does sanitization.

2023-10-27 17:35 UTC, mpharrigan commented
the bot is happy yay i'm basically a frontend dev now

2023-10-27 17:45 UTC, merged