Use pytest env for pytest CI check
quantumlib/Qualtran pull request #521
Opened 2023-11-17 18:17 UTC by mpharrigan

2023-11-17 18:56 UTC, fdmalone commented
our pytest env is insufficient / out of date it seems

2023-11-17 21:28 UTC, mpharrigan commented
sorry this is in progress to fix #517 among other issues.

This first commit gives the expected failure; I'll push a fix -- and we'll be left with the _other_ failures which then I'll think about how to fix :p

2023-11-17 22:34 UTC, mpharrigan commented
ok. This is now ready. I changed the pytest job to run the runtime tests with runtime dependencies and added a new, separate job to test the dev dependencies. Previously: the dev environment was used for testing so badly configured factorized dependencies could sneak by causing #517

2023-11-17 23:32 UTC, fdmalone commented on check/pytest-dev-tools
> +# Runs pytest on the repository.
runs pytest on dev_tools right?

2023-11-17 23:33 UTC, fdmalone commented on check/pytest-dev-tools
> +#     check/pytest [--flags for pytest] [file-paths-relative-to-repo-root]
fix docstring

2023-11-17 23:34 UTC, fdmalone requested changes
LGTM, just a nit about the docstring.

2023-11-18 00:44 UTC, mpharrigan commented
ahh I had that commit locally but didn't push it because I didn't want to have to start the CI over :D

2023-11-18 01:11 UTC, fdmalone commented
a [skip ci] might slide.

2023-11-20 17:36 UTC, mpharrigan commented
is this good now @fdmalone ?

2023-11-20 17:46 UTC, fdmalone approved these changes

2023-11-20 17:46 UTC, merged