Configure `LinearDepthGreaterThan()` bloq to allow for multiple target qubits
quantumlib/Qualtran pull request #782
Opened 2024-03-12 23:26 UTC by fpapa250

Add num_targets arg with default value 1 which allows us to have a bloq with multiple targets. Added functionality to classical simulation as well (for positive values).

2024-03-12 23:32 UTC, tanujkhattar requested changes
Can you explain what's the use case for this? The interface looks very unintuitive to me.

2024-03-12 23:32 UTC, tanujkhattar commented on qualtran/bloqs/arithmetic/comparison.py
> +    num_targets: int = 1
Change to `target_bitsize` ?

2024-03-12 23:36 UTC, fpapa250 commented
> Can you explain what's the use case for this? The interface looks very unintuitive to me.

I agree it's odd looking, but it's used in https://arxiv.org/abs/2306.08585 specifically in figure 7 for modular inverse. Open to thoughts on cleaning it up; this is what immediately made sense to me.

2024-03-12 23:39 UTC, fdmalone commented
Could you just add a CX gate controlled on the target of the original inequality target?

2024-03-12 23:42 UTC, fpapa250 commented
> Could you just add a CX gate controlled on the target of the original inequality target?

Neither target will always be flipped from 0 to 1. So I don't think that would be an equivalent operation.

2024-03-13 00:07 UTC, tanujkhattar commented on qualtran/bloqs/arithmetic/comparison.py
> +                ctrls, targets[i] = bb.add(MultiControlX(cvs=(1, 0)), ctrls=ctrls, x=targets[i])
Doing multiple Toffoli's is more expensive than doing an `And` and use a temporary ancilla to store the output; do a multi target CX controlled the result of this ancilla; and then uncompute the ancilla using `And(uncompute=True)`

2024-03-13 00:11 UTC, tanujkhattar commented
> Neither target will always be flipped from 0 to 1. So I don't think that would be an equivalent operation.

We can always use a temporary ancilla and use that to do a multi target CX

2024-03-18 23:48 UTC, mpharrigan commented
If you look at the construction, there already is an ancilla with the correct value that needs to be cnotted out to all the outputs. It's flanked by a compute/uncompute pattern per usual. 

In an ideal world, we'd have these first-class flanking operations so you could define a partial `GreaterThan` register; maybe with a `Side.DOWN` register; and you could combine it with whatever output-like bloq you want. e.g.

```python
MultiTarget(bloq=GreaterThan(), n_targets=5)
```

but that's sadly not the world we live in yet. So you could manually wrap the existing one-target greaterthan with a multitarget version composed of

 1. do greaterthan to output one bit
 2. do multi-target cnot to copy it to the n-1 other bits

all that being said -- this `LinearDepthGreaterThan` was introduced to track the referenced paper and it already doesn't really match the signature of `GreaterThan` so it might be fine to introduce the multi-target version directly for expediency

2024-10-02 00:24 UTC, closed without merging